services:    
    odiseo_preorder.form.type.show_buyer_buttons:
        class: Odiseo\Bundle\PreorderBundle\Form\Type\ShowBuyerButtonsFormType
        arguments:  [ "@service_container"]
          
    odiseo_preorder.form.factory.show_buyer_buttons:
        class: Odiseo\Bundle\PreorderBundle\Form\Factory\ShowBuyerButtonsFormFactory
        arguments:  [ "@form.factory" , "@odiseo_preorder.form.type.show_buyer_buttons", 'odiseo_preorder_show_buyer_buttons', %odiseo_preorder.model.preorder.class%]
    
    odiseo_preorder.form.type.show_vendor_buttons:
        class: Odiseo\Bundle\PreorderBundle\Form\Type\ShowVendorButtonsFormType
        arguments:  [ "@service_container"]
          
    odiseo_preorder.form.factory.show_vendor_buttons:
        class: Odiseo\Bundle\PreorderBundle\Form\Factory\ShowVendorButtonsFormFactory
        arguments:  [ "@form.factory" , "@odiseo_preorder.form.type.show_vendor_buttons", 'odiseo_preorder_show_vendor_buttons', %odiseo_preorder.model.preorder.class%]

    # Contract
    odiseo_preorder.form.handler.contract:
        class: Odiseo\Bundle\PreorderBundle\Form\Handler\ContractFormHandler
        arguments: [ "@service_container"]
    
    odiseo_preorder.form.type.contract:
        class: Odiseo\Bundle\PreorderBundle\Form\Type\ContractFormType
        arguments: [ "@router"]
          
    odiseo_preorder.form.factory.contract:
        class: Odiseo\Bundle\PreorderBundle\Form\Factory\ContractFormFactory
        arguments:  [ "@form.factory", "@odiseo_preorder.form.type.contract", 'odiseo_preorder_contract', %odiseo_preorder.model.preorder.class%]
                
    # Request
    odiseo_preorder.form.handler.request:
        class: Odiseo\Bundle\PreorderBundle\Form\Handler\RequestFormHandler
        arguments:  [ "@service_container"]
    
    odiseo_preorder.form.type.request:
        class: Odiseo\Bundle\PreorderBundle\Form\Type\RequestFormType
        arguments:  [ "@router"]
          
    odiseo_preorder.form.factory.request:
        class: Odiseo\Bundle\PreorderBundle\Form\Factory\RequestFormFactory
        arguments:  [ "@form.factory", "@odiseo_preorder.form.type.request", 'odiseo_preorder_request', %odiseo_preorder.model.preorder.class%]