services:    
    odiseo_preorder.form.type.show_buyer_buttons:
        class: Odiseo\Bundle\PreorderBundle\Form\Type\ShowBuyerButtonsFormType
        arguments:  [ "@service_container"]
        tags:
            - { name: form.type, alias: odiseo_preorder_show_buyer_buttons }
    
    odiseo_preorder.form.type.show_vendor_buttons:
        class: Odiseo\Bundle\PreorderBundle\Form\Type\ShowVendorButtonsFormType
        arguments:  [ "@service_container"]
        tags:
            - { name: form.type, alias: odiseo_preorder_show_vendor_buttons }

    # Contract
    odiseo_preorder.form.handler.contract:
        class: Odiseo\Bundle\PreorderBundle\Form\Handler\ContractFormHandler
        arguments: [ "@service_container"]
    
    odiseo_preorder.form.type.contract:
        class: Odiseo\Bundle\PreorderBundle\Form\Type\ContractFormType
        arguments: [ "@router"]
        tags:
            - { name: form.type, alias: odiseo_preorder_contract }
                
    # Request
    odiseo_preorder.form.handler.request:
        class: Odiseo\Bundle\PreorderBundle\Form\Handler\RequestFormHandler
        arguments:  [ "@service_container"]
    
    odiseo_preorder.form.type.request:
        class: Odiseo\Bundle\PreorderBundle\Form\Type\RequestFormType
        arguments:  [ "@router"]
        tags:
            - { name: form.type, alias: odiseo_preorder_request }