#Show and send request routes
odiseo_preorder_show_send_request:
    path:     /show-send-request/{productId}
    defaults: { _controller: "OdiseoPreorderBundle:Frontend/PreOrder:showSendRequestAction" }
    requirements:
        id:  \d+

odiseo_preorder_send_request:
    path:     /send-request/{id}
    defaults: { _controller: "OdiseoPreorderBundle:Frontend/PreOrder:sendRequest" }
    requirements:
        id:  \d+

#Show and send contract routes
odiseo_preorder_show_send_contract:
    path:     /show-send-contract/{id}/{buyerId}
    defaults: { _controller: "OdiseoPreorderBundle:Frontend/PreOrder:showSendContract" }
    requirements:
        id:  \d+

odiseo_preorder_send_contract:
    path:     /send-contract/{productId}/{buyerId}
    defaults: { _controller: "OdiseoPreorderBundle:Frontend/PreOrder:sendContract" }
    requirements:
        id:  \d+

#Details of preorder
odiseo_preorder_detail:
    path:    /detail/{id}
    defaults: { _controller: "OdiseoPreorderBundle:Frontend/PreOrder:detail" }
    requirements:
        id:  \d+